#+TITLE: GemDocs Guide
#+OPTIONS: toc:5
#+PROPERTY: header-args:ruby :results value :colnames no :hlines yes :exports both :dir "./"
#+PROPERTY: header-args:ruby :wrap example :session fat_fin_session
#+PROPERTY: header-args:ruby+ :prologue "require_relative 'lib/fat_fin'" :eval yes
#+PROPERTY: header-args:sh :exports code :eval no
#+PROPERTY: header-args:bash :exports code :eval no

* Overview
This gem contains ~rake~ tasks to facilitate the production of documentation
in other gems.

Right now, it provides tasks for:

- running the code block examples in a ~README.org~
- exporting ~README.org~ to Git-flavored markdown in ~README.md~
- generating yard documents for your repo, and
- copying the introductory contents of the README as a leading comment in your
  main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

* Installation

** Install the gem
Install the gem and add to the application's ~Gemfile~ by executing:

#+begin_src sh :eval no
  bundle add gem_docs
#+end_src

If bundler is not being used to manage dependencies, install the gem by executing:
#+begin_src sh :eval no
  gem install gem_docs
#+end_src

** Update Your ~Rakefile~
To use this gem place the following lines in your gem's ~Rakefile~:
#+begin_src ruby :eval no
  require "gem_docs"
  GemDocs.install
#+end_src

* Usage
** Generate ~README.md~ from ~README.org~
Now, you can write the ~README~ in Emacs org-mode, using all its features
including the execution of code blocks, and then export to git-flavored
markdown.

Github renders markdown better that it renders org files, so this helps with
the readability of the README on github.

#+begin_src ruby :eval no
  rake docs:readme
#+end_src

** Run the Code Blocks in README.org
You can invoke ~emacsclient~ to run all the examples in your ~README.org~ that
are set for evaluation:

#+begin_src ruby :eval no
 rake docs:examples
#+end_src

* Development
After checking out the repo, run `bin/setup` to install dependencies. Then,
run `rake spec` to run the tests. You can also run `bin/console` for an
interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake
install`. To release a new version, update the version number in `version.rb`,
and then run `bundle exec rake release`, which will create a git tag for the
version, push git commits and the created tag, and push the `.gem` file to
[rubygems.org](https://rubygems.org).

* Contributing
Bug reports and pull requests are welcome on GitHub at
https://github.com/ddoherty03/gem-docs.

* License
The gem is available as open source under the terms of the [MIT
License](https://opensource.org/licenses/MIT).
