# -*- mode: ruby -*-
# frozen_string_literal: true

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - ensuring a workflow or ci badge is present in the ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

# Gem Overview (auto-generated by gem_docs)
#
# * Overview
# This gem contains ~rake~ tasks to facilitate the production of documentation
# in other gems.
#
# Right now, it provides tasks for:
#
# - running the code block examples in a ~README.org~
# - exporting ~README.org~ to Git-flavored markdown in ~README.md~
# - generating yard documents for your repo, and
# - copying the introductory contents of the README as a leading comment in your
#   main gem library file so it gets picked up as an overview for ~ri~ and ~yri~

require "rake"
require "rake/dsl_definition"
require "fileutils"

module GemDocs
  require_relative "gem_docs/version"
  require_relative "gem_docs/config"
  require_relative "gem_docs/repo"
  require_relative "gem_docs/emacs"
  require_relative "gem_docs/overview"
  require_relative "gem_docs/yard"
  require_relative "gem_docs/badges"
  require_relative "gem_docs/tasks"

  # Auto-detect project root (handles being run from subdirs)
  def self.project_root
    here = Dir.pwd
    here = File.dirname(here) until !Dir['*.gemspec', 'Gemfile'].empty? || here == "/"
    here
  end
end
